
name: Plantory - Release Tag Generator
on:
    push:
        branches: [ main ]

defaults:
    run:
        shell: bash
        working-directory: .

jobs:
    build:
        name: Generate Tag
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Extract Version Code
              run: echo "##[set-output name=version;]$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
              id: extract_version_name
            - name: Generate Release Tag
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.extract_version_name.outputs.version }}
                  release_name: ${{ steps.extract_version_name.outputs.version }}
